import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'VIVIDNOW의 블로그',
  description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps }) {
  return (
    <html lang="en">
      <body> 
        <div className="navbar">
        <Link href="/" className="logo">VIVIDNOW의 블로그</Link>
        <Link href="/list">List</Link>
        <LoginBtn></LoginBtn>
        </div>
        </body>
    </html>
  )
}
