name: Dockerize-And-Push-ECR

on:
  push:
      branches:
      - main          # main 브랜치에 push시 실행
  pull_request:
    branches:
      - main          # main 브랜치에 PR시 실행

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}               # set this to your preferred AWS region, e.g. us-west-1
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}         # set this to your Amazon ECR URI
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}      # set this to your Amazon ECR repository name
  IMAGE_TAG: latest                                     # set this to your Amazon ECR repository tag name

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials            # AWS 로그인
      uses: aws-actions/configure-aws-credentials@v1
      with:                # AWS 로그인에 필요한 env, Github Secret에서 관리
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR    # ECR에 로그인
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR     
      id: build-image
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        # Build a docker container and
        # push it to ECR
        docker build --build-arg MONGODB_URI=$MONGODB_URI -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
